/project/{id}:
  get:
    operationId: Get Project
    description: Retrieve project by `id`
    security:
      - ApiKey: [ ]
    tags:
      - Project
    parameters:
      - name: id
        required: true
        description: Project ID
        in: path
        schema:
          type: string

    responses:
      404:
        $ref: "#/components/responses/NotFoundError"
      200:
        description: Successfully operation
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"

/project/{id}/start:
  get:
    description: Start all Project's checks
    operationId: Starts project
    tags:
      - Project
    parameters:
      - name: id
        required: true
        description: Project ID
        in: path
        schema:
          type: string
    responses:
      200:
        description: 'OL'

/api/project/{id}/job/{jobid}/results:
  get:
    description: Retrieve latest Project's checks results
    operationId: Get project results
    tags:
      - Project
    parameters:
      - name: id
        required: true
        description: Project ID
        in: path
        schema:
          type: string
      - name: jobid
        required: true
        description: Job ID
        in: path
        schema:
          type: string
    responses:
      200:
        description: "Ok"

/api/project/create:
  post:
    description: Create a new Project
    operationId: New Project
    tags:
      - Project
    responses:
      200:
        description: "ok"